AY2122S2-CS2103-W16-1/tp

docs/AboutUs.md

Corrected my name from Jane Doe to Loy Yoke Yue

Update yokeyue's section of AboutUs

---

src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/ReadOnlyUniBook.java
src/main/java/seedu/address/model/UniBook.java
src/main/java/seedu/address/model/module/Module.java
src/main/java/seedu/address/model/module/ModuleCode.java
src/main/java/seedu/address/model/module/ModuleList.java
src/main/java/seedu/address/model/module/ModuleName.java
src/main/java/seedu/address/model/module/exceptions/DuplicateModuleException.java
src/main/java/seedu/address/model/module/exceptions/ModuleNotFoundException.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/model/UniBookTest.java
src/test/java/seedu/address/testutil/ModuleBuilder.java

Added Module class and adapted the Model to function with this Module class.
Also added a ModuleBuilder so in future we are able to easily write tests (similar to PersonBuilder).
One more thing to take note: When you face weird errors with working with `Module`, make sure it is imported correctly i.e `import ...module.Module;` because Java has another default library called Module, the IDE always gets confused between those 2.
Things I need you guys to help with:
1) Help me look through for any logical errors or anything I may have overlooked
2) Help me double check if I forgot to change some of the javadoc comments from `Person` to `Module` - I already looked through once and seems fine.
3) In `Module.java` file, is using `List<Person>` for the list of students better, or …

Add Module to model

---

src/main/java/unibook/ui/MainWindow.java
src/main/java/unibook/ui/Ui.java
src/main/java/unibook/ui/UiManager.java

* Added 2 new methods to `UiManager` to check if module or person list is showing.

Add check on list view in UiManager

---

src/main/java/unibook/ui/cards/ModuleCard.java
src/main/resources/view/cards/ModuleListCard.fxml

Clean up module view gui

---

docs/UserGuide.md

Updated the UG for the add command portion.

Update UG for Add Command

---

src/main/java/unibook/model/UniBook.java
src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedGroupCode.java
src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedPerson.java
src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedProfessor.java
src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedStudent.java
src/test/java/unibook/storage/JsonAdaptedProfessorTest.java

- Edit storage to handle empty phone and email fields for people
- Reorganised storage methods to minimise code and enhance code reusability

Edit and refactor storage

---

docs/UserGuide.md

Updated user guide to reflect the new `ListCommand` features and syntax.

Update user guide for List Command changes

---

docs/UserGuide.md
src/main/java/unibook/commons/core/Messages.java
src/main/java/unibook/logic/commands/ListCommand.java
src/main/java/unibook/logic/parser/ListCommandParser.java
src/main/java/unibook/model/module/Module.java

As above^. Updated the user guide as well.
Format: `list g/w16-1 m/cs2103` whilst in the group page lists the specific group w16-1 from the module cs2103.

Add command to list specific group on module page

---

src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedGroup.java
src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedModule.java

- Fix minor flaw in storage that would allow certain duplicate values for some fields.

Fix storage flaws

---

src/main/java/unibook/MainApp.java

Change version number in MainApp to v1.3.1

---

docs/UserGuide.md

Edited the UG portion for Add Command as there were some typos and flaws as pointed out in the PE dry run.

Fix typos and shift examples around in UG for Add Command

---

src/main/java/unibook/model/module/Module.java

- Fix bug where able to add multiple modules of same code but different name #126 
- @yokester98 @sophiien take note of the changes - make sure you perform the check when adding and editing

Fix duplicate module bug

---

src/main/java/unibook/logic/commands/EditCommand.java
src/main/java/unibook/model/UniBook.java
src/main/java/unibook/model/module/Module.java
src/main/java/unibook/model/module/ModuleCode.java
src/main/java/unibook/model/module/group/Group.java
src/main/java/unibook/model/person/Office.java
src/main/java/unibook/model/person/UniquePersonList.java

- Set constraint on group name to allow for any non whitespace < 50 chars, and implemented it on creation of a Group object.
- Change constraint on module name to non whitespace < 50 chars.

Branch checks on group name

---

src/main/java/unibook/logic/commands/EditCommand.java
src/main/java/unibook/model/person/Email.java
src/main/java/unibook/model/person/Person.java
src/main/java/unibook/model/person/Phone.java
src/main/java/unibook/model/person/UniquePersonList.java
src/main/java/unibook/storage/JsonSerializableUniBook.java
src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedModule.java
src/test/data/JsonSerializableUniBookTest/duplicateEmailUniBook.json
src/test/data/JsonSerializableUniBookTest/duplicateGroupMeetingTimeUniBook.json
src/test/data/JsonSerializableUniBookTest/duplicateKeyEventUniBook.json
src/test/data/JsonSerializableUniBookTest/duplicateModuleCodeUniBook.json
src/test/data/JsonSerializableUniBookTest/duplicatePhoneUniBook.json
src/test/java/unibook/logic/commands/FindCommandTest.java
src/test/java/unibook/storage/JsonSerializableUniBookTest.java

- Added storage tests that tests the checks that are done to check for various duplicate fields in the unibook.json file, to make sure they are working and will detect duplicates.
- Fix a bug at #168 for edit command

Add duplicate entry in storage tests

---

docs/UserGuide.md
src/main/java/unibook/commons/core/Messages.java
src/main/java/unibook/logic/commands/EditCommand.java
src/main/java/unibook/logic/parser/EditCommandParser.java
src/main/java/unibook/logic/parser/ParserUtil.java
src/main/java/unibook/model/Model.java
src/main/java/unibook/model/ModelManager.java
src/main/java/unibook/model/UniBook.java
src/main/java/unibook/model/module/Module.java
src/main/java/unibook/model/module/ModuleCode.java
src/main/java/unibook/model/module/ModuleName.java
src/main/java/unibook/model/module/group/Group.java
src/main/java/unibook/model/person/Name.java
src/main/java/unibook/model/person/Office.java
src/main/java/unibook/model/person/UniquePersonList.java
src/test/java/unibook/logic/commands/AddCommandTest.java
src/test/java/unibook/logic/parser/EditCommandParserTest.java
src/test/java/unibook/model/person/UniquePersonListTest.java

Fixed UG for Edit Command based on bug report

Update UG for Edit Command

---

src/main/java/unibook/model/module/group/Group.java
src/main/java/unibook/ui/cards/ModuleAndGroupMiniCard.java
src/main/resources/view/Extensions.css
src/main/resources/view/cards/GroupCard.fxml
src/main/resources/view/cards/ModuleAndGroupMiniCard.fxml
src/main/resources/view/cards/ModuleCard.fxml
src/main/resources/view/cards/ModuleKeyEventCard.fxml
src/main/resources/view/cards/ProfessorCard.fxml
src/main/resources/view/cards/StudentCard.fxml

- Fix all sources of text cutting off due to long text in the GUI

Branch fix text cutting off

---

src/main/java/unibook/logic/commands/AddCommand.java
src/main/java/unibook/model/module/Module.java
src/main/java/unibook/model/module/ModuleCode.java
src/main/java/unibook/model/module/ModuleName.java
src/main/java/unibook/model/module/group/Group.java
src/main/java/unibook/model/person/Office.java
src/main/java/unibook/model/tag/Tag.java
src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedGroup.java
src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedModule.java
src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedModuleCode.java
src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedModuleKeyEvent.java
src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedStudent.java

- fix all input validation bugs like ability to add a group with just whitespaces for name (should not be allowed)

Fix input validation bugs

---

src/main/java/unibook/commons/core/Messages.java
src/main/java/unibook/logic/commands/DeleteCommand.java
src/main/java/unibook/logic/commands/EditCommand.java
src/main/java/unibook/logic/commands/FindCommand.java
src/main/java/unibook/logic/commands/ListCommand.java

Align error messages to UG particular those involving `Page` vs `View`

Align error messages to UG

---

src/main/java/unibook/logic/commands/AddCommand.java

When the user is on the group view, the list will be updated with the new group added. Fixes #189 
Also edited the error message displayed when adding a module so that the compulsory fields and the optional fields are indicated.

Add group to grouplist if group page is showing

---

docs/UserGuide.md
docs/team/benmurphyy.md

- Edited UG to fix bugs
- Updated my PPP

Add Bens Portfolio

---

docs/team/geraldneo567.md

Reverts AY2122S2-CS2103-W16-1/tp#212

Revert "Remove unnecessary title table at top of PPP"

---

docs/team/yokester98.md

Update the portion under PRs reviewed.

Branch update yokes ppp

---

docs/DeveloperGuide.md
src/test/java/unibook/model/module/ModuleCodeTest.java
src/test/java/unibook/model/module/ModuleKeyEventTest.java
src/test/java/unibook/model/module/ModuleListTest.java
src/test/java/unibook/model/module/ModuleNameTest.java

Added some test classes for `Module`.

Module tests

---

docs/team/sophiien.md
src/main/java/unibook/logic/commands/DeleteCommand.java
src/main/java/unibook/logic/commands/EditCommand.java
src/main/java/unibook/logic/parser/DeleteCommandParser.java
src/main/java/unibook/logic/parser/EditCommandParser.java
src/main/java/unibook/logic/parser/ParserUtil.java
src/main/java/unibook/model/person/Student.java
src/main/java/unibook/model/person/UniquePersonList.java
src/test/java/unibook/logic/commands/CommandTestUtil.java
src/test/java/unibook/logic/commands/EditCommandTest.java
src/test/java/unibook/logic/commands/EditPersonDescriptorTest.java
src/test/java/unibook/logic/parser/UniBookParserTest.java

- Remove todos and prints
- Fix EditPersonDescriptorTest

Fix EditPersonDescriptorTest 
